:toc: macro

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

toc::[]
:idprefix:
:idseparator: -
:reproducible:
:source-highlighter: rouge
:listing-caption: Listing

= Links to UI Libraries

WARNING: Hey there! Seems like you are still using the documentation of our legacy TypeScript repository. Since it won't be maintained anymore, we recommend you to checkout the new TypeScript page https://devonfw.com/docs/typescript/current/[here].

We have listed some links to UI libraries and common requested feature components we recommend. Here is the list

=== UI libraries:

WARNING: Hey there! Seems like you are still using the documentation of our legacy TypeScript repository. Since it won't be maintained anymore, we recommend you to checkout the new TypeScript page https://devonfw.com/docs/typescript/current/[here].
** https://material.angular.io/
** https://teradata.github.io/covalent/v3/#/
** https://www.primefaces.org/primeng/
** https://ng.ant.design/docs/introduce/en
** https://clarity.design/get-started/developing/angular/

=== Complex components or features:

WARNING: Hey there! Seems like you are still using the documentation of our legacy TypeScript repository. Since it won't be maintained anymore, we recommend you to checkout the new TypeScript page https://devonfw.com/docs/typescript/current/[here].

**  Grids/Data Tables
*** https://www.ag-grid.com/angular-data-grid/
*** https://github.com/swimlane/ngx-datatable - docs at https://swimlane.gitbook.io/ngx-datatable/
** Charts
*** https://github.com/xieziyu/ngx-echarts - Angular wrapper of https://echarts.apache.org/en/index.html
*** https://github.com/swimlane/ngx-charts - docs https://swimlane.gitbook.io/ngx-charts/
** i18n - internationalization
*** https://github.com/ngneat/transloco - docs at https://ngneat.github.io/transloco/