= NodeJS

WARNING: Hey there! Seems like you are still using the documentation of our legacy TypeScript repository. Since it won't be maintained anymore, we recommend you to checkout the new TypeScript page https://devonfw.com/docs/typescript/current/[here].

link:https://www.devonfw.com/[devonfw] is a platform which provides solutions to building business applications which combine best-in-class frameworks and libraries as well as industry proven practices and code conventions. devonfw is 100% Open Source (Apache License version 2.0) since the beginning of 2018.

devon4node is the NodeJS stack of devonfw. It allows you to build business applications (backends) using NodeJS technology in standardized way based on established best-practices.

devon4node is based on link:https://nestjs.com/[NestJS]. Nest (NestJS) is a framework for building efficient, scalable Node.js server-side applications. It uses progressive TypeScript and combines elements of OOP (Object Oriented Programming), FP (Functional Programming), and FRP (Functional Reactive Programming).

include::devon4node-architecture[leveloffset=1]

== Layers

WARNING: Hey there! Seems like you are still using the documentation of our legacy TypeScript repository. Since it won't be maintained anymore, we recommend you to checkout the new TypeScript page https://devonfw.com/docs/typescript/current/[here].

include::layer-controller[leveloffset=2]
include::layer-service[leveloffset=2]
include::layer-dataaccess[leveloffset=2]

== Guides

WARNING: Hey there! Seems like you are still using the documentation of our legacy TypeScript repository. Since it won't be maintained anymore, we recommend you to checkout the new TypeScript page https://devonfw.com/docs/typescript/current/[here].

include::guides-key-principles[leveloffset=2]
include::guides-code-generation[leveloffset=2]
include::guides-coding-conventions[leveloffset=2]
include::guides-dependency-injection[leveloffset=2]
include::guides-configuration-module[leveloffset=2]
include::guides-auth-jwt[leveloffset=2]
include::guides-swagger[leveloffset=2]
include::guides-typeorm[leveloffset=2]
include::guides-serializer[leveloffset=2]
include::guides-validation[leveloffset=2]
include::guides-logger[leveloffset=2]
include::guides-mailer[leveloffset=2]
include::guides-eslint-sonarqube-config[leveloffset=2]

== devon4node applications

WARNING: Hey there! Seems like you are still using the documentation of our legacy TypeScript repository. Since it won't be maintained anymore, we recommend you to checkout the new TypeScript page https://devonfw.com/docs/typescript/current/[here].

include::samples[leveloffset=2]
include::samples-step-by-step[leveloffset=2]
